### ISSUE TITLE
Any plans to update this to newer versions of the game?

### ISSUE THREAD

**Issue by uSkizzik** [henwill8/Replay#5]
Title says it all.

**Comment by CGray1234** [comment]
Henwill handed the project over to Metalit. 

The GitHub is here: https://github.com/Metalit/Replay

Also Hollywood, a dependency for Replay: https://github.com/Fernthedev/HollywoodQuest

**Comment by uSkizzik** [comment]
> Henwill handed the project over to Metalit.
> 
> The GitHub is here: https://github.com/Metalit/Replay
> 
> Also Hollywood, a dependency for Replay: https://github.com/Fernthedev/HollywoodQuest

Ahh that's cool... I'd assume Metalit's version is still under development as there's no builds yet, right?

**Comment by CGray1234** [comment]
There are test builds only available to Quest testers, but no stable public builds.

**Comment by uSkizzik** [comment]
Alright I guess I'll keep an eye out for it. Thanks!
